name: my_calendar
description: "A Assginment Mahindra Finance"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  url_launcher: ^6.2.3
  auto_route: ^7.8.4
  animated_toggle_switch: ^0.8.0
  table_calendar: ^3.0.9
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
